name: Patcher

on:
  workflow_dispatch:
    inputs:
      framework_url:
        description: 'Framework.jar URL'
        required: true
      services_url:
        description: 'Services.jar URL'
        required: false
      miui_services_url:
        description: 'Miui-services.jar URL'
        required: false
      api_level:
        description: 'API Level'
        required: true
        default: '33'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Download JARs
        run: |
          wget -O framework.jar ${{ github.event.inputs.framework_url }}
          if [ -n "${{ github.event.inputs.services_url }}" ]; then
            wget -O services.jar ${{ github.event.inputs.services_url }}
          fi
          if [ -n "${{ github.event.inputs.miui_services_url }}" ]; then
            wget -O miui-services.jar ${{ github.event.inputs.miui_services_url }}
          fi

      - name: Patch JARs
        run: |
          python3 patch.py --framework --services --miui-services

      - name: Prepare Magisk Module
        run: |
          mkdir -p magisk_module/system/framework
          if [ -f "framework_patched.jar" ]; then
            mv framework_patched.jar magisk_module/system/framework/framework.jar
          fi
          if [ -f "services_patched.jar" ]; then
            mv services_patched.jar magisk_module/system/framework/services.jar
          fi
          if [ -f "miui-services_patched.jar" ]; then
            mv miui-services_patched.jar magisk_module/system/framework/miui-services.jar
          fi
          cd magisk_module
          zip -r9 ../patched_module.zip .

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: patched_module.zip
          tag_name: ${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
