name: Webhook Workflow Trigger

on:
  repository_dispatch:
    types: [ trigger-android15, trigger-android16 ]

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - name: Trigger Android 15 Workflow
        if: github.event.action == 'trigger-android15'
        uses: actions/github-script@v6
        env:
          FRAMEWORK_PAT: ${{ secrets.FRAMEWORK_PAT }}
        with:
          github-token: ${{ secrets.FRAMEWORK_PAT }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'android15.yml',
              ref: 'master',
              inputs: {
                api_level: '${{ github.event.client_payload.api_level }}',
                device_name: '${{ github.event.client_payload.device_name }}',
                version_name: '${{ github.event.client_payload.version_name }}',
                framework_url: '${{ github.event.client_payload.framework_url }}',
                services_url: '${{ github.event.client_payload.services_url }}',
                miui_services_url: '${{ github.event.client_payload.miui_services_url }}',
                user_id: '${{ github.event.client_payload.user_id }}'
              }
            });

      - name: Trigger Android 16 Workflow
        if: github.event.action == 'trigger-android16'
        uses: actions/github-script@v6
        env:
          FRAMEWORK_PAT: ${{ secrets.FRAMEWORK_PAT }}
        with:
          github-token: ${{ secrets.FRAMEWORK_PAT }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'android16.yml',
              ref: 'master',
              inputs: {
                api_level: '${{ github.event.client_payload.api_level }}',
                device_name: '${{ github.event.client_payload.device_name }}',
                version_name: '${{ github.event.client_payload.version_name }}',
                framework_url: '${{ github.event.client_payload.framework_url }}',
                services_url: '${{ github.event.client_payload.services_url }}',
                miui_services_url: '${{ github.event.client_payload.miui_services_url }}',
                user_id: '${{ github.event.client_payload.user_id }}'
              }
            });
